In [31]:
import numpy as np

In [32]:
l=[1,2,3,4]

In [4]:
ar = np.array(l)

In [5]:
ar

array([1, 2, 3, 4])

In [30]:
ar.ndim

1

In [6]:
type(ar)

numpy.ndarray

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [9]:
type(np.asanyarray(l))

numpy.ndarray

In [10]:
b=np.matrix(l)

In [11]:
# if their is double squre then ==matrix 
b

matrix([[1, 2, 3, 4]])

In [12]:
type(b)

numpy.matrix

In [14]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [17]:
type(b)

numpy.matrix

In [13]:
a=np.array(l)

In [16]:
type(b)

numpy.matrix

In [14]:
c=a

In [15]:
c

array([1, 2, 3, 4])

In [16]:
c[0]=100

In [17]:
c

array([100,   2,   3,   4])

In [27]:
a

array([100,   2,   3,   4])

In [28]:
d=np.copy(a)

In [29]:
d

array([100,   2,   3,   4])

In [30]:
a

array([100,   2,   3,   4])

In [31]:
a[1]=400

In [32]:
a

array([100, 400,   3,   4])

In [33]:
b

matrix([[1, 2, 3, 4]])

In [3]:
np.fromfunction(lambda i,j :i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [4]:
np.fromfunction(lambda i,j :i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [7]:
iterable=(i*i for i in range(5))

In [16]:
np.fromiter(iterable,float)

array([], dtype=float64)

In [18]:
np.fromstring("234 234",sep=" ")

array([234., 234.])

In [20]:
np.fromstring("avs asd",sep=" ")

C:\Users\Adhinath\AppData\Local\Temp\ipykernel_11940\3795331283.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("avs asd",sep=" ")


array([], dtype=float64)

In [22]:
# numpy data types
l=[1,2,3,4,5]

In [33]:
ar = np.array(l)

In [34]:
ar

array([1, 2, 3, 4])

In [35]:
arr.ndim

1

In [36]:
l2=[[1,2,3],[2,3,4]]

In [37]:
ar2=np.array(l2)

In [38]:
ar2.ndim

2

In [99]:
ar2.size

6

In [39]:
ar2.shape

(2, 3)

In [41]:
arr.shape

(5,)

In [42]:
arr.dtype

dtype('int32')

In [43]:
ar2.dtype

dtype('int32')

In [44]:
ar22=np.array([(1.4,45,45),(23,34,5,)])

In [46]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 34. ,  5. ]])

In [48]:
ar22.dtype

dtype('float64')

In [49]:
list(range(0.1,5))

TypeError: 'float' object cannot be interpreted as an integer

In [51]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [52]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [53]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [56]:
np.linspace(1,100,21)

array([  1.  ,   5.95,  10.9 ,  15.85,  20.8 ,  25.75,  30.7 ,  35.65,
        40.6 ,  45.55,  50.5 ,  55.45,  60.4 ,  65.35,  70.3 ,  75.25,
        80.2 ,  85.15,  90.1 ,  95.05, 100.  ])

In [57]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [61]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [63]:
no=np.ones((3,2))

In [64]:
no*2

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [67]:
no*5

array([[5., 5.],
       [5., 5.],
       [5., 5.]])

In [68]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [70]:
np.empty((2,4))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 7.07502005e-321, 1.78019082e-306,
        1.37959740e-306]])

In [71]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [72]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [75]:
np.logspace(2,4,10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [76]:
arr=np.random.randn(3,4)

In [77]:
arr

array([[-1.24399685,  1.47197475, -0.2293754 ,  1.43303517],
       [ 1.10020736,  0.05186394,  1.58192883,  0.46868172],
       [ 0.83212307, -0.23782608, -0.91826847, -0.06796987]])

In [78]:
import pandas as pd

In [79]:
pd.DataFrame(arr)

0         1         2         3
0 -1.243997  1.471975 -0.229375  1.433035
1  1.100207  0.051864  1.581929  0.468682
2  0.832123 -0.237826 -0.918268 -0.067970

In [94]:
arr=np.random.rand(3,4)

In [95]:
arr

array([[0.57943511, 0.62739127, 0.1246802 , 0.86144757],
       [0.71911432, 0.54649002, 0.91924633, 0.09835538],
       [0.18563482, 0.8502853 , 0.34986452, 0.4118306 ]])

In [83]:
np.random.randint(1,100,(3,4))

array([[75, 32, 20, 45],
       [ 8, 17, 64, 21],
       [15, 94, 83, 66]])

In [100]:
pd.DataFrame(np.random.randint(1,100, (300,400))).to_csv("test.csv")

In [96]:
arr

array([[0.57943511, 0.62739127, 0.1246802 , 0.86144757],
       [0.71911432, 0.54649002, 0.91924633, 0.09835538],
       [0.18563482, 0.8502853 , 0.34986452, 0.4118306 ]])

In [103]:
arr.reshape(6,2)

array([[0.57943511, 0.62739127],
       [0.1246802 , 0.86144757],
       [0.71911432, 0.54649002],
       [0.91924633, 0.09835538],
       [0.18563482, 0.8502853 ],
       [0.34986452, 0.4118306 ]])