In [3]:
import numpy as np

In [4]:
l=[1,2,3,4]

In [5]:
ar = np.array(l)

In [6]:
ar

array([1, 2, 3, 4])

In [7]:
ar.ndim

1

In [8]:
type(ar)

numpy.ndarray

In [9]:
np.asarray(l)

array([1, 2, 3, 4])

In [10]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [11]:
type(np.asanyarray(l))

numpy.ndarray

In [12]:
b=np.matrix(l)

In [13]:
# if their is double squre then ==matrix 
b

matrix([[1, 2, 3, 4]])

In [14]:
type(b)

numpy.matrix

In [15]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [16]:
type(b)

numpy.matrix

In [17]:
a=np.array(l)

In [18]:
type(b)

numpy.matrix

In [19]:
c=a

In [20]:
c

array([1, 2, 3, 4])

In [21]:
c[0]=100

In [22]:
c

array([100,   2,   3,   4])

In [23]:
a

array([100,   2,   3,   4])

In [24]:
d=np.copy(a)

In [25]:
d

array([100,   2,   3,   4])

In [26]:
a

array([100,   2,   3,   4])

In [27]:
a[1]=400

In [28]:
a

array([100, 400,   3,   4])

In [29]:
b

matrix([[1, 2, 3, 4]])

In [30]:
np.fromfunction(lambda i,j :i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [31]:
np.fromfunction(lambda i,j :i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [32]:
iterable=(i*i for i in range(5))

In [33]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [34]:
np.fromstring("234 234",sep=" ")

array([234., 234.])

In [35]:
np.fromstring("avs asd",sep=" ")

C:\Users\Adhinath\AppData\Local\Temp\ipykernel_14176\3795331283.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("avs asd",sep=" ")


array([], dtype=float64)

In [36]:
# numpy data types
l=[1,2,3,4,5]

In [37]:
ar = np.array(l)

In [38]:
ar

array([1, 2, 3, 4, 5])

In [39]:
ar.ndim

1

In [40]:
l2=[[1,2,3],[2,3,4]]

In [41]:
ar2=np.array(l2)

In [42]:
ar2.ndim

2

In [43]:
ar2.size

6

In [44]:
ar2.shape

(2, 3)

In [45]:
ar.shape

(5,)

In [46]:
ar.dtype

dtype('int32')

In [47]:
ar2.dtype

dtype('int32')

In [48]:
ar22=np.array([(1.4,45,45),(23,34,5,)])

In [49]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 34. ,  5. ]])

In [50]:
ar22.dtype

dtype('float64')

In [51]:
# this gives only integer float is does not work in this case
list(range(5))

[0, 1, 2, 3, 4]

In [52]:
# in this d
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [53]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [54]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [55]:
np.linspace(1,100,21)

array([  1.  ,   5.95,  10.9 ,  15.85,  20.8 ,  25.75,  30.7 ,  35.65,
        40.6 ,  45.55,  50.5 ,  55.45,  60.4 ,  65.35,  70.3 ,  75.25,
        80.2 ,  85.15,  90.1 ,  95.05, 100.  ])

In [56]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [58]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [59]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [60]:
no=np.ones((3,2))

In [61]:
no*2

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [62]:
no*5

array([[5., 5.],
       [5., 5.],
       [5., 5.]])

In [63]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [64]:
np.empty((2,4))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 8.18172710e-321, 1.78019082e-306,
        1.37959740e-306]])

In [65]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [66]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [67]:
np.logspace(2,4,10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [68]:
arr=np.random.randn(3,4)

In [69]:
arr

array([[-0.60233374, -0.19976312,  1.51769724,  0.57315061],
       [-1.90613237, -0.19156578,  0.28686141, -0.46143659],
       [ 1.64046963,  1.53370451, -0.0919029 , -3.1795335 ]])

In [70]:
import pandas as pd

In [71]:
pd.DataFrame(arr)

0         1         2         3
0 -0.602334 -0.199763  1.517697  0.573151
1 -1.906132 -0.191566  0.286861 -0.461437
2  1.640470  1.533705 -0.091903 -3.179533

In [84]:
arr=np.random.rand(3,4)

In [73]:
arr

array([[0.86197079, 0.27330892, 0.64305835, 0.40074069],
       [0.88331362, 0.42290529, 0.16804606, 0.86540589],
       [0.45773221, 0.76980062, 0.93387656, 0.11936018]])

In [74]:
np.random.randint(1,100,(3,4))

array([[ 1, 45, 40,  5],
       [41,  2,  2, 85],
       [36, 82, 64,  5]])

In [75]:
pd.DataFrame(np.random.randint(1,100, (300,400))).to_csv("test.csv")

In [76]:
arr

array([[0.86197079, 0.27330892, 0.64305835, 0.40074069],
       [0.88331362, 0.42290529, 0.16804606, 0.86540589],
       [0.45773221, 0.76980062, 0.93387656, 0.11936018]])

In [77]:
arr.reshape(6,2)

array([[0.86197079, 0.27330892],
       [0.64305835, 0.40074069],
       [0.88331362, 0.42290529],
       [0.16804606, 0.86540589],
       [0.45773221, 0.76980062],
       [0.93387656, 0.11936018]])

In [85]:
ar1=np.random.randint(6,7)

In [87]:
np.random.randint(1,100,(6,7))

array([[92, 17, 79,  9, 31, 27, 81],
       [20,  2, 64, 81, 24, 82, 11],
       [57, 92, 70, 85, 14, 59, 88],
       [40, 57, 54, 51, 69, 31, 79],
       [76, 54, 81, 84, 93, 38, 34],
       [38, 69, 13, 37, 77, 66, 90]])

In [88]:
ar1=np.random.randint(6,7)

In [119]:
ar1=np.random.randint(1,100,(6,7))
ar1

array([[88, 11, 80, 95,  9, 12, 22],
       [26, 83,  1, 94, 59, 14,  6],
       [63, 73, 83, 10, 33, 20, 94],
       [50, 39, 93, 75, 32, 54, 69],
       [39, 58, 37, 65, 16, 59, 96],
       [51, 97, 73, 92, 83, 93,  5]])

In [94]:
ar2=np.random.randint(1,100,(6,7))
ar2

array([[95, 98, 74, 43, 47, 14, 93],
       [23, 72, 25, 67, 91, 41, 62],
       [47,  3, 57, 35, 40, 72, 33],
       [76, 65, 62, 27, 40, 94, 48],
       [78, 37,  1, 11, 53, 19, 78],
       [49, 57, 16, 11, 19, 54, 85]])

In [96]:
ar2>[50]

array([[ True,  True,  True, False, False, False,  True],
       [False,  True, False,  True,  True, False,  True],
       [False, False,  True, False, False,  True, False],
       [ True,  True,  True, False, False,  True, False],
       [ True, False, False, False,  True, False,  True],
       [False,  True, False, False, False,  True,  True]])

In [99]:
ar2[ar2>50]

array([95, 98, 74, 93, 72, 67, 91, 62, 57, 72, 76, 65, 62, 94, 78, 53, 78,
       57, 54, 85])

In [101]:
ar3=np.random.randint(1,50,(6,7))
ar3

array([[27, 38, 39,  6, 30, 29, 33],
       [ 2, 16,  7,  2,  5, 41, 27],
       [ 1, 47,  6, 26, 35, 41, 32],
       [27,  2, 48, 30, 26,  1, 45],
       [20, 45, 43, 16,  4, 14, 15],
       [ 5,  8, 39, 18,  6, 49,  5]])

In [102]:
ar3[2:4]

array([[ 1, 47,  6, 26, 35, 41, 32],
       [27,  2, 48, 30, 26,  1, 45]])

In [104]:
ar3[2:4,1:4]

array([[47,  6, 26],
       [ 2, 48, 30]])

In [108]:
ar4=np.random.randint(1,102,(6,7))
ar4

array([[ 49,  90,  52,  86,  31,  24,  18],
       [ 86,  98,  46,  70,  76,  49,  72],
       [ 99,  57,  33,  19,  94,   3, 101],
       [ 84,  28,  99,  79,  42,  25,  69],
       [ 53,  86,  65,  60,  14,  71,  84],
       [101,  27,  99,   2,  32,  54,  38]])

In [110]:
ar4[0][0]=50
ar4

array([[ 50,  90,  52,  86,  31,  24,  18],
       [ 86,  98,  46,  70,  76,  49,  72],
       [ 99,  57,  33,  19,  94,   3, 101],
       [ 84,  28,  99,  79,  42,  25,  69],
       [ 53,  86,  65,  60,  14,  71,  84],
       [101,  27,  99,   2,  32,  54,  38]])

In [112]:
arr1=np.random.randint(1,102,(3,3))
arr2=np.random.randint(1,102,(3,3))

In [113]:
arr1

array([[81, 92, 34],
       [ 7, 66, 50],
       [90, 81, 10]])

In [114]:
arr2

array([[68, 54, 45],
       [37, 38, 24],
       [47, 95, 93]])

In [115]:
arr1-arr2

array([[ 13,  38, -11],
       [-30,  28,  26],
       [ 43, -14, -83]])

In [116]:
arr1*arr2

array([[5508, 4968, 1530],
       [ 259, 2508, 1200],
       [4230, 7695,  930]])

In [118]:
arr1/arr2

array([[1.19117647, 1.7037037 , 0.75555556],
       [0.18918919, 1.73684211, 2.08333333],
       [1.91489362, 0.85263158, 0.10752688]])

In [120]:
arr1*arr2

array([[5508, 4968, 1530],
       [ 259, 2508, 1200],
       [4230, 7695,  930]])

In [121]:
arr1@arr2

array([[10510, 11100,  9015],
       [ 5268,  7636,  6549],
       [ 9587,  8888,  6924]])

In [140]:
arr4=np.zeros((3,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [142]:
raw=np.array([1,2,3])
raw

array([1, 2, 3])

In [143]:
arr4+raw

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [144]:
col=np.array([[1,2,3]])

In [145]:
col.T+arr4

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [149]:
a1=np.random.randint(1,102,(3,3))
arr1

array([[71, 96, 73],
       [42, 38, 80],
       [57, 19, 60]])

In [152]:
np.sqrt(a1)

array([[9.48683298, 6.4807407 , 8.94427191],
       [9.38083152, 6.63324958, 7.        ],
       [7.07106781, 8.42614977, 7.07106781]])

In [153]:
np.exp(a1)

array([[1.22040329e+39, 1.73927494e+18, 5.54062238e+34],
       [1.65163625e+38, 1.28516001e+19, 1.90734657e+21],
       [5.18470553e+21, 6.83767123e+30, 5.18470553e+21]])

In [154]:
np.log2(ar2)

array([[5.12928302, 4.39231742, 5.55458885, 5.        , 4.95419631,
        5.12928302, 4.64385619],
       [5.20945337, 1.5849625 , 2.5849625 , 3.5849625 , 4.7548875 ,
        3.169925  , 3.32192809],
       [3.45943162, 1.5849625 , 4.80735492, 5.42626475, 4.08746284,
        5.42626475, 4.7548875 ],
       [5.        , 5.169925  , 4.39231742, 4.        , 4.80735492,
        4.24792751, 5.20945337],
       [4.95419631, 5.39231742, 3.45943162, 3.80735492, 4.52356196,
        1.5849625 , 5.61470984],
       [4.80735492, 4.95419631, 4.80735492, 5.45943162, 4.70043972,
        4.7548875 , 3.5849625 ]])